// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Data.Persistence
{
    public partial class CartItem
    {
        public int IdCartItem { get; set; }
        public int ProductId { get; set; }
        public int Amount { get; set; }
        public int OrderId { get; set; }
        public decimal? Price { get; set; }

        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}