// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Data.Persistence
{
    public partial class Product
    {
        public Product()
        {
            CartItem = new HashSet<CartItem>();
        }

        public int IdPorduct { get; set; }
        public string NameProduct { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string UrlImage { get; set; }
        public decimal Price { get; set; }
        public int Stock { get; set; }
        public int ShopId { get; set; }

        public virtual Shop Shop { get; set; }
        public virtual ICollection<CartItem> CartItem { get; set; }
    }
}