// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Data.Persistence
{
    public partial class Roles
    {
        public Roles()
        {
            User = new HashSet<User>();
        }

        public int IdRol { get; set; }
        public string Rol { get; set; }

        public virtual ICollection<User> User { get; set; }
    }
}