// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Data.Persistence
{
    public partial class Shop
    {
        public Shop()
        {
            Product = new HashSet<Product>();
        }

        public int IdShop { get; set; }
        public string NameShop { get; set; }
        public string Address { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }
}