// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Data.Persistence
{
    public partial class User
    {
        public User()
        {
            Order = new HashSet<Order>();
        }

        public string Name { get; set; }
        public string LastName { get; set; }
        public int IdUser { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public int RolId { get; set; }
        public int? ShopId { get; set; }

        public virtual Roles Rol { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}